modid = "hexcasting"
book_id = "hexcasting:thehexbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    { modid="hexcasting", external=false },
]
export_dir = "src/hexdoc_lsp/_export/generated"
